### PR TITLE
Update proto.go to send height to miner in job

### PR DESCRIPTION
**Pull request by SmokinCache**
Added height for CN/R

### CODE REVIEW

**Comment by SmokinCache** [comment]
Tested with SRBminer 1.8.0

**Comment by gr8form** [comment]
FWIW, I tested this patch, as well as, your other ones using a build against the current monero project tag of 14.02 using SRBminer 1.8.1, but am getting red line messages displaying within the miner.  Log shows: 
"[2019-03-22 14:29:49] pool_have_job: Pool sent a new job [ID: 52]
[2019-03-22 14:29:49] Block height = 0 for V4 job - DeviceID 0 (Thread 0) [report to pool]".  

I'm unsure whether to be concerned, miner shows shares accepted & valid shares in pool though have yet to find a block to know whether it accepts, orphans or rejects.

**Comment by SmokinCache** [comment]
Miner should report current block height as below

[2019-03-22 13:43:24] pool_have_job: Pool sent a new job[10541], block height 1796541 (ID: 1167)
[2019-03-22 13:43:29] miner_result: Sending user result to pool

**Comment by gr8form** [comment]
Agree it should.  Just rebuilt from scratch using current master git & monero git with checkout tags/v0.14.0.0 -b v0.14.0.0 per readme, then updated both proto.go and miner.go with your updates; same result.  Is there another file to the repo that you've updated beyond these 2 files?  Thanks in advance!

**Comment by SmokinCache** [comment]
Those two edits must be made before issuing the make command for the pool. The Monero build is another independent action that these two changes does not effect. I have forked this repository and will update the readme there.

**Comment by gr8form** [comment]
Never mind, found your repo, works properly now!  Also, FYI, applied it to latest monero release tag of 14.02 and also works - well done.

**Comment by SmokinCache** [comment]
Glad it worked! Good Luck!

**Pull request closed without merging**
