### PR TITLE
CryptoNight variant from v7

### PR DESCRIPTION
**Pull request by stoffu**
I've mined a few blocks on v8 testnet with this patch.

### CODE REVIEW

**Comment by sammy007** [comment]
Need to merge https://github.com/monero-project/monero/pull/3350 first.

**Comment by stoffu** [comment]
Right. I've built the pool by pulling the Monero code from 3350.

BTW, Aeon will also likely have the same POW change from protocol version 2 (which is not completely decided/agreed yet), so please incorporate the change when it's decided. Thank you!

**Comment by sammy007** [comment]
Then there is a config option needed to specify when and on what block version variants take effect, shitcoins will likely also pull changes and some are already at v7.

**Comment by stoffu** [comment]
Maybe this should be handled by you rather than me. Closing.

**Pull request merged**
