### PR TITLE
Added height to getJob for CN/R miner

### PR DESCRIPTION
**Pull request by SmokinCache**

### CODE REVIEW

**Comment by sammy007** [comment]
Are you sure existing miners feel good with this patch?

**Comment by gr8form** [comment]
I can confirm that smokinCache's repo for both this patch #100 & #99 works on mainnet for monero and when tested on testnet I found blocks with rewards showing up in testnet wallet.  I am using in production though haven't found a block yet :(

**Comment by SmokinCache** [comment]
gr8form is the only other user that has reached out and confirmed testing. I tested on stagenet and mainnet with SRB. I did not test on the testnet as #103 references.

**Comment by khooj** [comment]
Used this repo and SmokinCache's fork as reference implementation. I can confirm that #100 and #99 fixed pool's work. Tested with xmr-stak 2.10.4 and xmrig 2.14.1 on stagenet

**Comment by dagonharett** [comment]
I can also confirm that this PR (#100) together with #99 fixes block creation. Tested on mainnet with xmr-stak `2.10.4`: block found and credited in wallet.
Sorry for taking so long to reply, I had to wait until I found a block. Also, my apologies for missing this important detail on my PR (#97).

**Pull request closed without merging**
